version: "3.2"
services:
  app:
    build: ./app
    container_name: marvelScrapper_C
    links: 
      - db
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
#  script:
#    build: ./app
#    container_name: pokepy_scriptPost
#    links:
#      - db
#    volumes:
#      - type: bind
#        source: ./app
#        target: /usr/src/app
#    command: ["python", "./populate.py"]
  db:
    build: ./db
    container_name: marvelDB_A
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "marvel123"
      POSTGRES_DB: "marvelHeroes"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    container_name:  pgadmin4_B
    environment:
      PGADMIN_DEFAULT_EMAIL: "marvel@marvel.com"
      PGADMIN_DEFAULT_PASSWORD: "marvel123"
    ports:
     - "80:80"
    depends_on:
     - db
    links:
     - db



